org.gradle.jvmargs=-Xmx6G -Dfabric.loom.multi.project.isolation=true
kotlin.daemon.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.configureondemand=false
maven_group=com.palordersoftworks.brokenstarsmpmod
mod_version=2.0.0-26.2
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_version=0.156.0+26.2
paper_api_version=26.2.build.+
spigot_api_version=26.2-R0.1-SNAPSHOT
velocity_api_version=3.4.0-SNAPSHOT
legacy_mod_version=1.7.0-26.1.2
legacy_minecraft_version=26.1.2
legacy_loader_version=0.19.2
legacy_loom_version=1.16.1
legacy_fabric_version=0.149.1+26.1.2
legacy_yarn_mappings=26.1.2+build.1
quilt_minecraft_version=1.21.11
quilt_loader_version=0.30.0-beta.3
quilt_loom_version=1.14.3
quilt_qsl_version=10.0.0-alpha.5+1.21.1
