pluginManagement {
    repositories {
        maven { name = 'FabricMC'; url = 'https://maven.fabricmc.net/' }
        maven { name = 'PaperMC'; url = 'https://repo.papermc.io/repository/maven-public/' }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'Brokenstarsmp-Official-Mod'

include 'common'
include 'fabric'
include 'paper'
include 'spigot'
include 'velocity'