pluginManagement {
    repositories {
        maven {
            name = 'PalorderHosting'
            url = 'https://maven.palorderhosting.net/releases'
        }
        maven {
            name = 'FabricMC'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}
