plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'maven-publish'
    id 'org.jetbrains.kotlin.jvm' version '2.3.10'
    id("com.gradleup.shadow") version "9.4.1"
}

group = project.maven_group
version = project.mod_version

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven { url 'https://maven.nucleoid.xyz' }
    maven { url 'https://maven.squiddev.cc/' }
}
configurations {
    luaShadow
    Shadow
}
dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modImplementation "net.fabricmc:fabric-language-kotlin:1.13.8+kotlin.2.3.0"

    compileOnly "io.github.llamalad7:mixinextras-common:0.5.3"
    annotationProcessor "io.github.llamalad7:mixinextras-common:0.5.3"

    modImplementation include("eu.pb4:polymer-core:0.15.2+1.21.11")

    modLocalRuntime "party.iroiro.luajava:luajit:4.1.0"
    luaShadow "party.iroiro.luajava:luajit:4.1.0"
}

loom {
    accessWidenerPath = file("src/main/resources/brokenstarsmp.accesswidener")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

tasks.named("shadowJar") {
    archiveClassifier.set("shadow")
    configurations = [project.configurations.luaShadow, project.configurations.Shadow]
}

tasks.named("remapJar") {
    dependsOn tasks.named("shadowJar")
    inputFile.set(tasks.named("shadowJar").flatMap { it.archiveFile })
}