pluginManagement {
    repositories {
        maven {
            name = 'PalorderHosting'
            url = 'https://maven.palorderhosting.net/releases'
        }
        maven {
            name = 'FabricMC'
            url = 'https://maven.fabricmc.net/'
        }
        maven { url = 'https://maven.neoforged.net' }
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
        gradlePluginPortal()
    }
}