plugins {
    id 'org.quiltmc.loom' version "${quilt_loom_version}"
}

group = rootProject.maven_group
version = rootProject.mod_version

base {
    archivesName = 'brokenstarsmp-quilt'
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.quilt_minecraft_version}"
    mappings "org.quiltmc:quilt-mappings:${rootProject.quilt_minecraft_version}+build.1"
    modImplementation "org.quiltmc:quilt-loader:${rootProject.quilt_loader_version}"
    modImplementation "org.quiltmc:qsl:${rootProject.quilt_qsl_version}"
}

processResources {
    inputs.property 'version', project.version
    filesMatching('quilt.mod.json') { expand version: project.version }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}
