# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G -Dfabric.loom.multi.project.isolation=true
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16.1

#Fabric api
fabric_version=0.149.1+26.1.2
# Mod Properties
mod_version=1.7.0-26.1.2
maven_group=com.palordersoftworks.brokenstarsmpmod
archives_base_name=server
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.configureondemand=false