org.gradle.jvmargs=-Xmx2G -Dfabric.loom.multi.project.isolation=true

minecraft_version=1.21.11

maven_group=com.palordersoftworks.brokenstarsmpmod
archives_base_name=server
mod_version=1.7.0-1.21.11

fabric_loader=0.17.2
fabric_version=0.138.4+1.21.11

loom_version=1.13.6
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=false