pluginManagement {
    repositories {
        maven {
            name = 'PalorderHosting'
            url = 'https://maven.palorderhosting.net/releases'
        }
        maven {
            name = 'PaperMC'
            url = 'https://repo.papermc.io/repository/maven-public/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
